AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  hostedZone:
    Type: String
    Default: "prescriptionsforpatients.national.nhs.uk"
    Description: >
      Domain name we are going to be hosting

Resources:
  Zone:
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: "My hosted zone for prescriptionsforpatients.national.nhs.uk"
      Name: !Ref hostedZone
  nsRootHostedZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref Zone
      Name: !Join [".", ["dev", !Ref hostedZone, ""]]
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
          "ns-1403.awsdns-47.org",
          "ns-979.awsdns-58.net",
          "ns-25.awsdns-03.com",
          "ns-1854.awsdns-39.co.uk",
        ]
    DependsOn: Zone
