name: dependencies
description: install dependencies
runs:
  using: composite
  steps:
    - name: Install asdf
      shell: bash
      run: |
        rm -rf ~/.asdf
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.2
        echo ". $HOME/.asdf/asdf.sh" >> ~/.bashrc
        echo ". $HOME/.asdf/completions/asdf.bash" >> ~/.bashrc
    - name: Install asdf plugins
      shell: bash
      run: |
        asdf plugin-add direnv
        asdf plugin-add java
        asdf plugin add python
        asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
        asdf plugin add poetry https://github.com/asdf-community/asdf-poetry.git
        asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
    - name: Run asdf install
      shell: bash
      run: asdf install
