name: dependencies
description: install dependencies
runs:
  using: composite
  steps:
    - name: Install asdf & plugins
      shell: bash
      run: ./.github/scripts/install-asdf.sh
    - name: Run asdf install
      shell: bash
      run: |
        PATH="$PATH:$HOME/.asdf/bin/"
        asdf install
