name: dependencies
description: install dependencies
runs:
  using: composite
  steps:
    # - name: asdf install and plugins
    - name: asdf install
      shell: bash
      run: |
        whoami
        sudo su - ubuntu
        whoami
        asdf install
