name: dependencies
description: install dependencies
runs:
  using: composite
  steps:
    - name: Install asdf & plugins
      shell: bash
      run: ./.github/scripts/install-asdf.sh
    - name: Run asdf install
      shell: bash
      run: |
        echo "$HOME/.asdf/bin/" >> $GITHUB_PATH
        echo $PATH
        asdf install
