name: dependencies
description: install dependencies
runs:
  using: composite
  steps:
    # - name: asdf install and plugins
    - name: asdf install and reshim
      shell: bash
      run: |
        asdf install
