name: dependencies
description: install dependencies
runs:
  using: composite
  steps:
    - name: asdf install
      shell: bash
      run: |
        echo $PATH
        export PATH="$PATH:$HOME/.asdf/bin/"
        echo $PATH
        asdf install
