name: build

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  quality-checks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - run: ./.github/actions/scripts/fix-path.sh
        shell: bash
      - uses: ./.github/actions/dependencies/
      - run: make install
      - run: make check-licenses
      - run: make lint
      - run: make test
