name: build

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  quality-checks:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Remove existing asdf
        run: rm -rf ~/.asdf
      - name: Install asdf and dependencies
        uses: asdf-vm/actions/install@v2
      - run: make install
      - run: make check-licenses
      - run: make lint
      - run: make test
