name: build

on:
  pull_request:
    types: ['opened', 'reopened']
    branches: ['AEA-**']

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      # remove once self-hosted runners are available
      - uses: ./.github/actions/temp-dependencies/
      
      # enable once self-hosted runners are available
      # - name: dependencies
      #   uses: ./.github/actions/dependencies/

      - run: make install
      - run: make check-licenses
      - run: make lint
      - run: make test
