name: build

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Install asdf and dependencies
        uses: asdf-vm/actions/install@v2

      - name: make install
        run: make install

      - name: run check-licenses
        run: make check-licenses

      - name: run lint
        run: make lint

      - name: run unit tests
        run: make test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ vars.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: github-actions

      - uses: actions/github-script@v6
        name: get issue number
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

      - shell: bash
        name: deploy code
        env:
          PULL_REQUEST_ID: ${{steps.get_issue_number.outputs.result}}
        run: |
          artifact_bucket=$(aws cloudformation list-exports --output json | \
            jq -r '.Exports[] | select(.Name == "dev-ci-resources:ArtifactsBucket") | .Value' |grep -o '[^:]*$')
          artifact_bucket_prefix=PR-${PULL_REQUEST_ID}
          template_file=dev-deploy.yaml
          stack_name=dev-pr-${PULL_REQUEST_ID}-deployment
          cloud_formation_execution_role=$(aws cloudformation list-exports --output json | \
              jq -r '.Exports[] | select(.Name == "dev-ci-resources:CloudFormationExecutionRole") | .Value' )
          make sam-deploy-PR
