name: build

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  quality-checks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/dependencies/
      - name: Fix PATH and make install
        run: |
          echo "/home/ubuntu/.asdf/installs/poetry/1.3.1/bin" >> $GITHUB_PATH
          echo "/home/ubuntu/.asdf/installs/python/3.8.15/bin" >> $GITHUB_PATH
          make install
      - run: make check-licenses
      - run: make lint
      - run: make test
