name: get commit id

on:
  workflow_call:

jobs:
  get_commit_id:
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit ID
        id: commit_id
        run: |
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Echo Commit ID
        run: |
          echo ${{ steps.commit_id.outputs.commit_id }}
