name: get commit id

on:
  workflow_call:

jobs:
  get_commit_id:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.commit_id.outputs.COMMIT_ID }}
    steps:
      - name: Get Commit ID
        id: commit_id
        run: |
          echo "commit_id=${{ github.sha }} >> $GITHUB_OUTPUT"
