name: quality checks

on: workflow_call

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: github-actions
  
      - name: Install asdf and dependencies
        uses: asdf-vm/actions/install@v2

      - name: make install
        run: make install

      - name: run check-licenses
        run: make check-licenses

      - name: run lint
        run: make lint

      - name: run unit tests
        run: make test
