name: release

on:
  push:
    branches: ['main']
    tags: [v**]

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      # dependencies can be removed once self-hosted runners are being used #
      # additions to this block need to be added to the scripts and packer template in the ci repo #
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: |
          pip install -U pip
          pip install poetry
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      # /dependencies #

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - run: make install
      - run: make check-licenses
      - run: make lint
      - run: make test
