name: release

on:
  push:
    branches: ['main']
    tags: ['v**']

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      # remove once self-hosted runners are available
      - uses: ./.github/actions/temp-dependencies/
      
      # enable once self-hosted runners are available
      # - name: dependencies
      #   uses: ./.github/actions/dependencies/

      - run: make install
      - run: make check-licenses
      - run: make lint
      - run: make test
