name: release

on:
  push:
    branches: [main]
    tags: [v**]

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  quality-checks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/fix-path/
      - uses: ./.github/actions/dependencies/
      - run: make install
      - run: make check-licenses
      - run: make lint
      - run: make test
