name: release

on:
  push:
    branches: [main]
    tags: [v**]

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  quality-checks:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v2
      - run: asdf --version
      - run: make install
      - run: make check-licenses
      - run: make lint
      - run: make test
