name: release_code

on:
  workflow_call:
    inputs:
      TEMPLATE_FILE:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string
      ARTIFACT_BUCKET_PREFIX:
          required: true
          type: string
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string

jobs:
  release_code:
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets[format('{0}', inputs.CLOUD_FORMATION_DEPLOY_ROLE_SECRET_NAME)] }}
          role-session-name: github-actions

      - uses: actions/download-artifact@v3
        name: download template_file
        with:
          name: ${{ inputs.TEMPLATE_FILE }}

      - shell: bash
        name: release code
        run: |
          echo "STACK_NAME: ${{ inputs.STACK_NAME}}"
          echo "TEMPLATE_FILE: ${{ inputs.TEMPLATE_FILE}}"
          echo "TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT}}"
          export artifact_bucket=$(aws cloudformation list-exports --output json | \
            jq -r '.Exports[] | select(.Name == "ci-resources:ArtifactsBucket") | .Value' |grep -o '[^:]*$')
          export artifact_bucket_prefix=${{ inputs.ARTIFACT_BUCKET_PREFIX }}
          export template_file=${{ inputs.TEMPLATE_FILE }}
          export stack_name=${{ inputs.STACK_NAME }}
          export cloud_formation_execution_role=$(aws cloudformation list-exports --output json | \
              jq -r '.Exports[] | select(.Name == "ci-resources:CloudFormationExecutionRole") | .Value' )
          make sam-deploy-package
