name: package_release

on:
  workflow_call:
    inputs:
      TEMPLATE_FILE:
        required: true
        type: string
      ARTIFACT_BUCKET_PREFIX:
        required: true
        type: string
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true
        type: string

jobs:
  package_release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Install asdf and dependencies
        uses: asdf-vm/actions/install@v2

      - name: make install
        run: make install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ inputs.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: github-actions

      - shell: bash
        name: package code
        run: |
          export artifact_bucket=$(aws cloudformation list-exports --output json | \
            jq -r '.Exports[] | select(.Name == "dev-ci-resources:ArtifactsBucket") | .Value' |grep -o '[^:]*$')
          export artifact_bucket_prefix=${{ inputs.ARTIFACT_BUCKET_PREFIX }}
          export template_file=${{ inputs.TEMPLATE_FILE }}
          make sam-package

      - uses: actions/upload-artifact@v3
        name: upload template_file
        with:
          name: ${{ inputs.TEMPLATE_FILE }}
          path: ${{ inputs.TEMPLATE_FILE }}
