name: sam package code

on:
  workflow_call:

jobs:
  sam_package_code:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

        # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf and dependencies
        uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4

      - name: make install
        run: make install

      - shell: bash
        name: package code
        run: |
          cp .tool-versions ~/
          rm -rf .aws-sam
          export PATH=$PATH:$PWD/node_modules/.bin
          make sam-build
          cp Makefile .aws-sam/build/
          cp samconfig_package_and_deploy .aws-sam/build/ 

      - uses: actions/upload-artifact@v3
        name: upload build artifact
        with:
          name: packaged_code
          path: .aws-sam/build
