name: package_release

on:
  workflow_call:
    inputs:
      TEMPLATE_FILE:
        required: true
        type: string
      ARTIFACT_BUCKET_PREFIX:
        required: true
        type: string
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true

jobs:
  package_release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

        # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf and dependencies
        uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4

      - name: make install
        run: make install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: github-actions

      - shell: bash
        name: package code
        run: |
          cp .tool-versions ~/
          export PATH=$PATH:$PWD/node_modules/.bin
          make sam-build

      - uses: actions/upload-artifact@v3
        name: upload build artifact
        with:
          name: packaged_code
          path: .aws-sam/build
